apiVersion: v1
kind: Service
metadata:
  name: eangelou
  labels:
    app: eangelou
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    protocol: TCP
    name: ssh
  selector:
    app: eangelou
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: eangelou
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eangelou
    spec:
      containers:
      - name: eangelou
        image: eangelou/cslab
        ports:
        - containerPort: 22
