apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    protocol: TCP
    name: ssh
  selector:
    app: ubuntu
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ubuntu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        ports:
        - containerPort: 22
